### ISSUE TITLE
No site do evento não tem link para o Call4papers

### ISSUE THREAD

**Issue by rochacbruno** [pythonbrasil/pythonbrasil11-site#1]
http://pythonbrasil.github.io/pythonbrasil11-site/

**Comment by zokis** [comment]
Tem sim na área de palestrantes tem um vazio:

https://github.com/pythonbrasil/pythonbrasil11-site/blob/gh-pages/_site/index.html#L160

"Clique aqui e seja um palestrante na Python Brasil 2015."

**Comment by rochacbruno** [comment]
@zokis devo estar com o grau de miopia muito alto.. haha não vi o link!!!

valei!
