### ISSUE TITLE
Façam camisetas Baby Look para as meninas ! 

### ISSUE THREAD

**Issue by PKpacheco** [pythonbrasil/pythonbrasil11-site#17]

**Comment by rochacbruno** [comment]
:+1: 

Também acho que poderiam colocar umas camiseta a venda! Eu gostaria de ter comprado para dar de presente.

**Comment by PKpacheco** [comment]
Seria bem legal até pq muita gente gostou da camiseta preta.

**Comment by turicas** [comment]
Galera, isso tem a ver com um tema que eu já estava pensando em tocar há algum tempo: que tal fazermos camisetas da PythonBrasil, independente da conferência?
A ideia surgiu porque teve uma galera que curtiu bastante a da PythonBrasil[8](no Rio) e pensamos então em fazer uma camiseta parecida, mas tirando as referências da conferência ("[8]", a data, "Rio de Janeiro", patrocinadores etc.). Podíamos juntar uma galera interessada em comprar essas camisetas, modificar a arte e mandar fazer. Eu ainda tenho contato e o fonte das artes da PyBr[8], então não seria muito complicado (o que seria mais complicado é a validação do pagamento de todo mundo).

**Comment by turicas** [comment]
De qualquer forma, acho que o ideal seria criar essa issue no repositório https://github.com/pythonbrasil/associados, já que provavelmente não vamos mais querer fazer camisetas da PyBr[11] porque ela já passou. :smile: 
Criei lá: https://github.com/pythonbrasil/associados/issues/121

Acho que poderíamos fechar essa issue aqui (que não se refere diretamente à PyBr[11]) e seguir por lá. Que acha, @PaolaKatherine?

**Comment by PKpacheco** [comment]
sim @turicas
